### ISSUE TITLE
LWG3515 [stacktrace.basic.nonmem]: operator<< should be less templatized

### ISSUE THREAD

**Issue by jwakely** [cplusplus/papers#1298] opened 2022-09-07 16:41 UTC
LWG would like LEWG to review [LWG 3515](https://cplusplus.github.io/LWG/issue3515) and decide whether the proposed resolution is the right direction.

This is a new C++23 feature, so it would be good to get this resolved in time for C++23.

**Comment by brycelelbach** [comment] 2022-09-27 19:44
## 2022-09-27 Library Evolution Telecon

[LWG3515](https://wg21.link/LWG3515): [stacktrace.basic.nonmem]: `operator<<` should be less templatized

[2022-09-27 Library Evolution Telecon Minutes](http://wiki.edg.com/bin/view/Wg21telecons2022/LWG3515#Library-Evolution-2022-09-27)

__Chair:__ Bryce Adelstein Lelbach

__Minute Taker:__ Steve Downey

__Start:__ 2022-09-27 12:04 Eastern

__POLL: Send the proposed resolution for LWG3515 ([stacktrace.basic.nonmem]: `operator<<` should be less templatized) to Library for C++23 classified as B2 - Improvement, to be confirmed with a Library Evolution electronic poll.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|7|6|1|0|0|

__Attendance:__ 20

__Outcome:__ Consensus in favor.

__End:__ 12:15

### Summary

This issue points out that it's unnecessary for `stacktrace`'s output streaming operator to be templated on the stream's character and character traits type, because `stacktrace` always passes a `string` to the stream, requiring that the character type be `char` and the character traits type be `char_traits<char>`. The proposed resolution is to detemplatize these operators.

We discussed whether we want `stacktrace` to support wide strings. Most felt that this could be explored in the future and shouldn't stop us from making this simplification now. We could always add more overloads in the future.

### Next Steps

Take an electronic poll to send the proposed resolution for LWG3515 ([stacktrace.basic.nonmem]: `operator<<` should be less templatized) to Library for C++23 classified as B2 - Improvement, to be confirmed with a Library Evolution electronic poll.

**Comment by JeffGarland** [comment] 2022-11-10 16:08
Issue has been set to immediate after LWG review in Kona. 

https://wiki.edg.com/bin/view/Wg21kona2022/LWG20221107-EA


poll: move LWG3515 to ready?

F | A | N
-- | -- | --
9 | 0 | 2

**Comment by JeffGarland** [comment] 2023-01-09 20:09
LWG3515 is now in the Working Paper - closing this issue.

**Closed by JeffGarland** 2023-01-09 20:09 UTC
Labels: LWG, C++23, IS, B2 - improvement, size - tiny
