### ISSUE TITLE
LWG4043 `"ASCII"` is not a registered character encoding

### ISSUE THREAD

**Issue by tahonermann** [cplusplus/papers#1810] opened 2024-03-09 17:30 UTC
https://cplusplus.github.io/LWG/issue4043

**Comment by tahonermann** [comment] 2024-03-09 17:41
SG16 discussed this issue during its [2024-02-21 meeting](https://github.com/sg16-unicode/sg16-meetings/blob/master/README.md#february-21st-2024). The following polls were taken:

- **Poll 1: Approve the addition of "ASCII" as an alias for the US-ASCII IANA encoding.**
  - Attendees: 9
  - No objection to unanimous consent.

SG16 review is complete and this now rests solely in LWG's capable hands.

**Comment by jwakely** [comment] 2024-03-12 01:09
The issue is Tentatively Ready and will be in the Tokyo polls.

**Comment by JeffGarland** [comment] 2024-06-17 03:06
This was approved with https://wg21.link/P3180R0 in Tokyo.  Closing.

**Comment by JeffGarland** [comment] 2024-06-17 03:07
This was approved with https://wg21.link/P3180R0 in Tokyo.  Closing.

**Closed by JeffGarland** 2024-06-17 03:07 UTC
Labels: LWG
