### ISSUE TITLE
P0901 Size feedback in operator new

### ISSUE THREAD

**Issue by jensmaurer** [cplusplus/papers#1361] opened 2022-11-09 20:04 UTC
[P0901R9](https://wg21.link/p0901r9) Size feedback in operator new (Andrew Hunter, Chris Kennelly, Thomas Köppe)

**Comment by erichkeane** [comment] 2022-11-09 20:12
We should support new expressions as a fully fledged feature that exposes all the details of hte allocation functions.

| SF | F | N | A | SA |
|--|--|--|--|--|
| 0 | 2 | 5 | 9 |3 |

Result: Consensus Against

We should leave new expressions ignorant of new feature and only add a point mechanism to deal with these new functions.

| SF | F | N | A | SA |
|--|--|--|--|--|
| 1 | 3 | 4 | 3 | 4 |

Result: No consensus

EwG is interested in a facility similar to the one proposed in D0901R10, and would like to see this paper again.
	
| SF | F | N | A | SA |
|--|--|--|--|--|
| 2 | 7 | 5 | 0 | 3 |

Result: Weak consensus

**Comment by Mick235711** [comment] 2022-11-09 21:20
We seems to already have #18 for this...

**Comment by erichkeane** [comment] 2022-11-09 23:51
THis is a duplicate of #18, so transferring Kona's history and future history to that.

**Closed by erichkeane** 2022-11-09 23:51 UTC
Labels: EWG
